[project]
name = "cymbal-retail-agent"
version = "0.2.0"
description = "Cymbal Retail Agent"
authors = [
    {name = "Sai Saran Vaidyanathan",email = "ssvaidyanathan@google.com"}
]
license = {text = "Apache License 2.0"}
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-adk == 1.36.1",
    "google-cloud-aiplatform[adk,agent-engines] >= 1.100.0, < 2.0.0",
    "python-dotenv >= 1.1.1, < 2.0.0",
    "fastapi >= 0.116.0",
    "google-cloud-secret-manager >= 2.24.0, < 3.0.0",
    "litellm"
]

[dependency-groups]
dev = [
    "google-adk == 1.36.1"
]
deployment = [
    "absl-py >= 2.2.2",
    "google-cloud-aiplatform[adk,agent-engines] >= 1.100.0"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"