apiVersion: inference.networking.x-k8s.io/v1alpha2
kind: InferenceObjective
metadata:
  name: food-review
spec:
  priority: 1
  poolRef:
    group: inference.networking.k8s.io
    name: vllm-qwen2.5-1.5b-instruct
---
apiVersion: inference.networking.x-k8s.io/v1alpha2
kind: InferenceObjective
metadata:
  name: base-model
spec:
  priority: 2
  poolRef:
    group: inference.networking.k8s.io
    name: vllm-qwen2.5-1.5b-instruct
---
apiVersion: inference.networking.x-k8s.io/v1alpha2
kind: InferenceObjective
metadata:
  name: base-model-cpu
spec:
  priority: 2
  poolRef:
    group: inference.networking.k8s.io
    name: vllm-qwen2.5-1.5b-instruct