# Common
region=europe-west1
project=apigee-x-jog
project_number=1014194238001
index_endpoint_dns=1502911790
default_model=gemini-2.5-pro
default_fallback_model=gemini-2.5-flash

# Routing
routing_index_endpoint_id=2671852837914279936
routing_deployed_index_id=semantic_routing_index_endpoint_deployment_v2
routing_index_id=293125401918570496

# Cache
cache_index_endpoint_id=4609526577590435840
cache_deployed_index_id=semantic_cache_index_endpoint_deployment
cache_index_id=4040120291890823168
